import Constants from './Constants';

export default {
  peep: 5,
  measuredPressure: 25,
  plateauPressure: 20,
  respiratoryRate: {
    name: 'Patient Rate',
    upperLimit: 35,
    lowerLimit: 8,
    unit: 'BPM',
    setValue: 20,
    value: 20,
  },
  tidalVolume: 200,
  ieRatio: '1:2',
  vti: 100,
  vte: 400,
  minuteVentilation: 100,
  inspiratoryTime: 3,
  expiratoryTime: 5,
  fiO2: {
    name: 'FiO2',
    upperLimit: 100,
    lowerLimit: 50,
    unit: '%',
    setValue: 75,
    value: 75,
  },
  flowRate: 23,
  PIP: 50,
  mode: 'VCV',
  graphPressure: new Array(Constants.GraphLength).fill(40),
  graphVolume: new Array(Constants.GraphLength).fill(200),
  graphFlow: new Array(Constants.GraphLength).fill(150),
  alarms: [],
};
